### ISSUE TITLE
Power BI learning path query

### ISSUE THREAD

**Issue by SeanKe11y** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#223]
I'm wondering should **Learning Path 8: Visualize data with Power BI** still be included seeing as Power BI was removed as a required skill for PL-200 in the Jan 12 2024 update?

**Comment by julians1966** [comment]
Power BI still exists in the skills measured but only as consuming within apps and using with Power Pages:
- Add Microsoft Power BI dashboards and reports in a model-driven app
- Describe advanced Power Pages features, including document management, search, multi-step forms, and Power BI

Note: The Job Task Analysis that defines the course does cover more than makes it into the exam. Some tasks in the JTA marked as are training only and do not appear in the skills measured on the Study Guide. 

You cannot explain how to embed Power BI without explaining what Power BI is so that is why it is still included but has been much reduced in size. 

The slides also include other reporting options that cover the task in the skills measured
- Determine which reporting options to use including embedding Microsoft Power BI or using Fetch-based reports

**Comment by SeanKe11y** [comment]
OK, that makes perfect sense, thanks for the clear response, and for the great January update PR!!
